---
# tasks file for avinetworks.docker
- name: Docker | Include Specific Variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Docker | Storage Driver
  include: "storage_drivers/{{ storage_driver }}.yml"
  when: storage_driver is defined

- name: Docker | Start Installation
  include: "{{ ansible_pkg_mgr }}.yml"

- name: Docker | Configure
  include: "config.yml"

- name: Docker | Start the Docker Process and Start at Boot
  service: name=docker enabled=yes state=started
